### ISSUE TITLE
Make "Remix" Button larger in play link

### ISSUE THREAD

**Issue by chloeatplay** [toolness/mobile-microgame-maker#28]
propbably good to be one of the standard red or blue buttons.

**Comment by toolness** [comment]
Ok, it's actually kinda hard to reuse styles from the web app because of the standalone nature of the exported HTML, so I didn't use the standard buttons... instead I made it kinda like a "fork me on github" ribbon in 5cb97240e66a05ae1792142e7bb599686941ff57:

![2015-01-28_8-19-40](https://cloud.githubusercontent.com/assets/124687/5938181/78a63b8e-a6c6-11e4-9296-0f2dd0d2aece.png)

The ribbon gets bigger as the viewport does, so it's noticeable without being too intrusive on iPhones as well as desktops.
