### ISSUE TITLE
 UX fixes for adding sprites 

### ISSUE THREAD

**Issue by chloeatplay** [toolness/mobile-microgame-maker#8]
Did some intense testing this morning with friends.

A general comment since i am worried that what we have right now is not in shape for next weeks playtest yet:

Adding sprites through the little window when you click <+> definitely an improvement but still it's super confusing to have all those drop-downs. Essentially, we want to remove some functionality at this point... and keep it as simple as possible. The more we can use gestures versus dropdown the better, i.e. instead of having 3 dropdowns to set position, do it wt drag on the stage directly etc...

![mobile minigame maker 2014-11-28 11-21-55](https://cloud.githubusercontent.com/assets/1945209/5230222/f3be3c8c-76f0-11e4-9d80-42d93f212057.png)

**Comment by toolness** [comment]
So the reason that the user can't drag the sprite on the stage directly is because randomness/procedural generation is a huge part of the replayability of microgames--for instance, if the fly always started out in the same position in flyswat, it would be really easy (and boring) to win over and over.

Because of this, we can't assume that the sprite will be in a static, fixed place that the author can drag around in an editor (this is why we have them specify it with the radio buttons). The area at the top of the app isn't a "stage" but an actual minigame player, and any number of things in the minigame can be randomly/procedurally generated at the beginning of play. This is basically how WarioWare DIY's editor UI works.

In fact, with the exception of the Blockly stuff, right now our UI is basically a very simplified version of WarioWare DIY's UI--the difference right now is that we don't have a tutorial to ease folks into it, and we also don't have the [wizard](http://designinginterfaces.com/patterns/wizard/)-style interface that makes it easier to understand the UI by always leading the user through a series of steps--but which also makes it harder to change one specific part of the game's configuration, since the one thing an author might want to change may be buried in the 5th step of a wizard UI. My hope is that since WarioWare DIY was designed to be used by kids/non-coders, ours can too.

**Comment by toolness** [comment]
What do you mean by "why is sushi1 and the one below sushi"? The sprite is a game object... I guess we could call it just `sushi` and then name any future occurrences of sushi `sushi2`, `sushi3`, et cetera, but each game object needs its own unique name so that Blockly code can reference it unambiguously. 

It's also part of the scaffolding that allows one to go from making things in this editor to actually coding things in JS by tinkering with the game's source code--if we don't provide reference points that make it easy for the user intuit relationships between the JS code and the editor, then the JS code will be inscrutable. This is actually part of the reason I went with "sushi1" instead of "sushi", as "sushi" is the name of the sprite<em>sheet</em> that the sprite uses, not the sprite itself, and giving the two the same name might make the generated JS code confusing. (It's also useful to note that WarioWare DIY doesn't even let you name objects--it just calls them `Object 1`, `Object 2`, and so forth, as MMM used to do.)

**Comment by chloeatplay** [comment]
See #5 for some ideas regarding the sprite dropdown

**Comment by chloeatplay** [comment]
I m going to close this issue- since we are addressing at #5
